# _config.yml
# bundle exec jekyll build -v
# (bundle exec) jekyll serve
# JEKYLL_GITHUB_TOKEN=********** jekyll serve


######### MAIN CONFIG ######################
repository: sudeshjethoe/sudeshjethoe.github.io
title: Dynamic Automation
email: sudesh@dynamicautomation.nl
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

######### SOCIAL SETTINGS ###################
# google: analytics
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-97485794-1"
    anonymize_ip: true

# google: social links in google search results
social:
  type: Person
  name: "Sudesh Jethoe"
  links:
    - "https://twitter.com/sudeshjethoe"
    - "https://www.linkedin.com/in/sudeshjethoe"

# twitter: attribute site to twitter account
twitter:
  username: "sudeshjethoe"

# opengraph (twitter, facebook)
og_image: "/apple-touch-icon.png"

######### MINIMAL MISTAKES THEME CONFIG ######
minimal_mistakes_skin: air
search: true

markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes"
# output
permalink: /:categories/:title/
paginate: 5
paginate_path: /articles/page:num/
timezone: Europe/Amsterdam

# site logo on frontpage
logo: /assets/images/tux_logo.svg
# default teaser image if not set in post
teaser: /assets/images/teaser_thumbnail_default.jpg

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jemoji

######### BEGIN SITE FRONT DEFAULTS ##########
author:
  name: "Sudesh Jethoe, MSc. MBA."
  avatar: "https://www.gravatar.com/avatar/300a064a668a97b462ef1eed24f346f5?size=250"
  bio: "Engineering, Leadership, Cloud, Big Data"
  location: "Amsterdam"
  links:
     - label: "Email"
       icon:  "fas fa-fw fa-envelope-square"
       url:   "mailto:&#115;&#117;&#100;&#101;&#115;&#104;&#64;&#100;&#121;&#110;&#97;&#109;&#105;&#99;&#97;&#117;&#116;&#111;&#109;&#97;&#116;&#105;&#111;&#110;&#46;&#110;&#108;" # sudesh@dynamicautomation.nl
     - label: "WhatsApp"
       icon:  "fab fa-fw fa-whatsapp"
       url:   "https://wa.me/31634069057?text=Hi+Sudesh%2c+I+would+like+to+get+in+touch+with+you+for%3a+"
     - label: "My Resume"
       icon:  "fas fa-file-pdf"
       url:   "/assets/cv.pdf"
     - label: "LinkedIn"
       icon:  "fab fa-fw fa-linkedin"
       url:   "https://www.linkedin.com/in/sudeshjethoe"
     - label: "GitHub"
       icon:  "fab fa-fw fa-github"
       url:   "https://github.com/sudeshjethoe"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/sudeshjethoe"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/sudeshjethoe"

defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      # additional classes for styling blogposts
      classes:
        - blogpost
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _portfolio
  - scope:
      path: ""
      type: posts
    values:
      # additional classes for styling portfolio pages
      classes:
        - portfoliopost
      layout: single
      read_time: true
      author_profile: false
      share: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
