# _config.yml
# bundle exec jekyll build -v
# (bundle exec) jekyll serve
# JEKYLL_GITHUB_TOKEN=********** jekyll serve
repository: sudeshjethoe/sudeshjethoe.github.io


title: Dynamic Automation
email: sudesh@dynamicautomation.nl
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://dynamicautomation.nl" # the base hostname & protocol for your site, e.g. http://example.com

twitter_username: sudeshjethoe
github_username:  sudeshjethoe

minimal_mistakes_skin: default
search: true

# build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes"
# output
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: "Europe/Amsterdam"


include:
  - _pages

plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
  - jekyll-remote-theme

author:
  name: "Sudesh Jethoe"
  avatar: "https://www.gravatar.com/avatar/300a064a668a97b462ef1eed24f346f5?size=250"
  bio: "Placeholder bio!!"
  links:
     - label: "GitHub"
       icon:  "fab fa-fw fa-github"
       url:   "https://github.com/sudeshjethoe"
     - label: "My Resume"
       icon:  "fas fa-file-pdf"
       url:   "/assets/cv.pdf"
     - label: "LinkedIn"
       icon:  "fab fa-linkedin"
       url:   "https://www.linkedin.com/in/sudeshjethoe"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

